check args better

diff --git a/ripsacd b/ripsacd
--- a/ripsacd
+++ b/ripsacd
@@ -56,6 +56,11 @@ eval "$(
 Artist="$(echo "${Artist}" | tr -d '/\\;/')"
 Title="$(echo "${Title}" | tr -d '/\\;/')"
 
+if [ -z "${Artist}" ] || [ -z "${Title}" ]; then
+  2>&1 echo "Could not get Artist or Title info from {sacd_player}"
+  exit 2
+fi
+
 output="${HOME}/sacd/${Artist}/${Title} (SACD)"
 umask 002
 mkdir -pv "${output}"
